export default {
  restaurant: 'Restaurant',
  name: 'pyzza pizza',
  startOrder: 'START ORDER >',
  login: {
    closeEye: 'eye-slash',
    openEye: 'eye',
    loginStatusFailedMess: 'Sign in failed',
    loginStatusSucceededMess: 'Sign in succeeded',
    invalidEmailMess: 'Invalid email',
    invalidPassMess: 'Invalid password',
    okTxt: 'OK',
    txtEmailPlaceholder: 'Email/Phone number',
    txtPasswordPlaceholder: 'Password',
    txtLoginTitle: 'Login',
    btnLogin: 'LOGIN',
    btnSingUp: 'Sign up',
  },
  signUp: {
    txtFirstNamePlaceholder: 'First name',
    txtLastNamePlaceholder: 'Last name',
    txtEmailPlaceholder: 'Email',
    txtPhoneNumberPlaceholder: 'Phone number',
    txtPasswordPlaceholder: 'Password',
    txtConfirmPasswordPlaceholder: 'Confirm password',
    invalidNameMess: 'Invalid name',
    invalidPhoneNumMess: 'Invalid phone number',
    invalidEmailMess: 'Invalid email',
    invalidPassMess: 'Invalid password',
    invalidConfirmPassMess: 'Password not match',
    signUpFailedMess: 'Sign up failed',
  },
  checkOut: {
    txtData: 'Date: ',
    txtTotalBill: 'Total Bill: ',
  },
  userInfo: {
    firstName: ' FIRST NAME',
    lastName: 'LAST NAME',
    phoneNum: 'PHONE NUMBER ',
    email: 'EMAIL',
    address: 'ADDRESS',
  },
};
