export default {
  restaurant: 'Restaurant',
  name: 'pyzza pizza',
  startOrder: 'START ORDER >',
  login: {
    closeEye: 'eye-slash',
    openEye: 'eye',
    loginStatusFailedMess: 'Sign in failed',
    loginStatusSucceededMess: 'Sign in succeeded',
    invalidEmailMess: 'Invalid email',
    invalidPassMess: 'Invalid password',
    okTxt: 'OK',
    txtEmailPlaceholder: 'Email/Phone number',
    txtPasswordPlaceholder: 'Password',
    txtLoginTitle: 'Login',
    btnLogin: 'LOGIN',
    btnSingUp: 'Sign up',
  },
  signUp: {
    txtFirstNamePlaceholder: 'First name',
    txtLastNamePlaceholder: 'Last name',
    txtEmailPlaceholder: 'Email',
    txtPhoneNumberPlaceholder: 'Phone number',
    txtPasswordPlaceholder: 'Password',
    txtConfirmPasswordPlaceholder: 'Confirm password',
    invalidNameMess: 'Invalid name',
    invalidPhoneNumMess: 'Invalid phone number',
    invalidEmailMess: 'Invalid email',
    invalidPassMess: 'Invalid password',
    invalidConfirmPassMess: 'Password not match',
    signUpFailedMess: 'Sign up failed',
    signUpSucceededMess: 'Sign up succeeded',
  },
  checkOut: {
    txtCheckoutTitle: 'CHECK OUT',
    txtYourOrder: 'Your order',
    txtEmptyCart: 'Empty cart ',
    txtConfirmBtn: 'CONFIRM ',
    txtGoBackBtn: ' GO BACK',
    txtData: 'Date: ',
    txtTotalBill: 'Total Bill: ',
  },
  userInfo: {
    firstName: ' FIRST NAME',
    lastName: 'LAST NAME',
    phoneNum: 'PHONE NUMBER ',
    email: 'EMAIL',
    address: 'ADDRESS',
  },
  productItem: {
    txtSizeL: 'Size L :',
    txtSizeM: 'Size M :',
    txtSizeS: 'Size S :',
  },
  myCart: {
    headerTitle: 'My Cart',
    timesIconName: 'times',
    arrowRightIconName: 'arrow-circle-right',
    txtTotalItem: 'items / Total cost : ',
    txtCheckoutBtn: 'CHECK OUT ',
  },
  categoriesScreen: {
    iconBarsName: 'bars',
    iconCartName: 'shopping-cart',
  },
  drawer: {
    signOutMess: 'User signed out',
    signInRequireMess: 'You must sign in first',
    signedInMess: 'You have been signed in',
  },
};
